
# This file is automatically generated, you probably don't want to edit this

testMeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "testMeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL, ...) {

            super$initialize(
                package="testMe",
                name="testMe",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                default=NULL,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..residuals <- jmvcore::OptionOutput$new(
                "residuals")
            private$..multi_residuals <- jmvcore::OptionOutput$new(
                "multi_residuals")

            self$.addOption(private$..dep)
            self$.addOption(private$..residuals)
            self$.addOption(private$..multi_residuals)
        }),
    active = list(
        dep = function() private$..dep$value,
        residuals = function() private$..residuals$value,
        multi_residuals = function() private$..multi_residuals$value),
    private = list(
        ..dep = NA,
        ..residuals = NA,
        ..multi_residuals = NA)
)

testMeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "testMeResults",
    inherit = jmvcore::Group,
    active = list(
        info = function() private$.items[["info"]],
        residuals = function() private$.items[["residuals"]],
        multi_residuals = function() private$.items[["multi_residuals"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Testing")
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Some Info",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="value", 
                        `type`="number", 
                        `title`="A number")),
                clearWith=list(
                    "dep")))
            self$add(jmvcore::Output$new(
                options=options,
                name="residuals",
                title="Residuals Vales",
                varTitle="`TEST_${ dep }`",
                varDescription="test values",
                clearWith=list(
                    "dep")))
            self$add(jmvcore::Output$new(
                options=options,
                name="multi_residuals",
                title="Multicolumn",
                varDescription="test values",
                clearWith=list(
                    "dep")))}))

testMeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "testMeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "testMe",
                name = "testMe",
                version = c(0,0,1),
                options = options,
                results = testMeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Testing
#'
#' Something here
#' 
#'
#' @examples
#' \dontrun{
#' some code here
#'}
#' @param data the data as a data frame
#' @param dep a string naming the dependent variable from \code{data},
#'   variable must be numeric
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$residuals} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$multi_residuals} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
testMe <- function(
    data,
    dep = NULL) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("testMe requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- testMeOptions$new(
        dep = dep)

    analysis <- testMeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

